services:
  - type: web
    name: climate-alert-platform-api
    runtime: python
    repo: https://github.com/Isa18121999/Climate-alert--platform
    branch: main
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: climate-alert-platform-db
          property: connectionString
      - key: KAFKA_BOOTSTRAP_SERVERS
        sync: false
      - key: KAFKA_USERNAME
        sync: false
      - key: KAFKA_PASSWORD
        sync: false
      - key: KAFKA_SECURITY_PROTOCOL
        value: SASL_SSL
      - key: KAFKA_SASL_MECHANISM
        value: PLAIN
      - key: KAFKA_ALERT_TOPIC
        value: climate-alerts

  - type: cron
    name: climate-alert-platform-monitor
    runtime: python
    repo: https://github.com/Isa18121999/Climate-alert--platform
    branch: main
    schedule: "*/15 * * * *"
    buildCommand: pip install requests
    startCommand: python scripts/monitor_render.py
    autoDeploy: true
    envVars:
      - key: API_URL
        value: https://climate-alert-platform-api.onrender.com

  - type: pserv
    name: climate-alert-platform-db
    plan: free
    runtime: postgres
    region: oregon
    postgresMajorVersion: '18'
